### ISSUE TITLE
新建用户接口错误

### ISSUE THREAD

**Issue by kingdeezhao** [icxcat/egg-RESTfulAPI#1]
async create(payload) {
    const { ctx, service } = this
    const role = await service.role.fetch(payload.role)
    if (!role) {
      ctx.throw(404, 'role is not found')
    }
    payload.password = await this.ctx.genHash(payload.password)
    return ctx.model.User.create(payload)
  }

没有service.role.fetch  方法
应该是 show 方法

**Comment by heimi-block** [comment]
@kingdeezhao 已修复，部分接口变动。
