### ISSUE TITLE
如何把权限和角色加进去？

### ISSUE THREAD

**Issue by kkys4bfgp75be9p** [icxcat/egg-RESTfulAPI#2]
如何把权限和角色加进去？

**Comment by heimi-block** [comment]
我那个只是一个简单的模板，如果你要做权限可以在model角色表RoleSchema里新增privileges字段，字段里可以放权限组['c', 'd']，比如c表示创建，d表示删除等，或者privileges里进一步指定身份标识privileges: admin, superAdmin 然后前端根据这个名称限制显示的功能~~
