### ISSUE TITLE
想问下，mongodb里面的数据初始化脚本有吗

### ISSUE THREAD

**Issue by zhefengdangyu** [icxcat/egg-RESTfulAPI#3]
想问下，mongodb里面的数据如何初始化

**Comment by heimi-block** [comment]
@zhefengdangyu models已经把数据模型设计好了，你调用对应接口传入载体自动创建数据即可；
如果你是要在第一次启动EGG应用时，创建一些初始化数据；你可以在service里写一个init脚本，里面执行的是mongoose的插入方法,然后调用service即可；
eg: // service init.js
`async init() {`
`  const { ctx, service } = this`
  `await Promise.all([ctx.service.role.create({name: 'developer'}), 
                                   ctx.service.user.create({mobile: '177****7725',......}), ......])`
  `}`

**Comment by llh1187** [comment]
> @zhefengdangyu models已经把数据模型设计好了，你调用对应接口传入载体自动创建数据即可；
> 如果你是要在第一次启动EGG应用时，创建一些初始化数据；你可以在service里写一个init脚本，里面执行的是mongoose的插入方法,然后调用service即可；
> eg: // service init.js
> `async init() {`
> ` const { ctx, service } = this`
> `await Promise.all([ctx.service.role.create({name: 'developer'}), ctx.service.user.create({mobile: '177****7725',......}), ......])`
> `}`

用postman按照你的写法传送数据，老是返回500错误：
{
    "code": 500,
    "error": "Cast to ObjectId failed for value \"developer\" at path \"_id\" for model \"Role\""
}
看了代码，发现是因为service/user里面：
 service.role.show(payload.role)这一句话，传了‘developer’（按照你的示例）过去，正确的参数应该为role表中‘developer’的_id才对。
