### ISSUE TITLE
你这里没有任何关于egg-jwt的使用啊

### ISSUE THREAD

**Issue by Erchoc** [icxcat/egg-RESTfulAPI#4]
token那里生成？存储在哪？我在您的代码中一点都没看到啊

**Comment by heimi-block** [comment]
请你先熟悉jwt的运行机制和存储机制，https://jwt.io/
再熟悉egg-jwt，https://github.com/okoala/egg-jwt
然后仔细看demo代码...

 // userAccess
  router.post('/api/user/access/login', controller.userAccess.login)
  router.get('/api/user/access/current', app.jwt, controller.userAccess.current)

  async login(payload) {
    const { ctx, service } = this
    const user = await service.user.findByMobile(payload.mobile)
    if(!user){
      ctx.throw(404, 'user not found')
    }
    let verifyPsw = await ctx.compare(payload.password, user.password)
    if(!verifyPsw) {
      ctx.throw(404, 'user password is error')
    }
    // 生成Token令牌
    return { token: await service.actionToken.apply(user._id) }
  }

// ActionTokenService
'use strict'

const Service = require('egg').Service

class ActionTokenService extends Service {
  async apply(_id) {
    const {ctx} = this
    return ctx.app.jwt.sign({
      data: {
        _id: _id
      },
      exp: Math.floor(Date.now() / 1000) + (60 * 60 * 24 * 7)
    }, ctx.app.config.jwt.secret)
  }
}

module.exports = ActionTokenService

**Comment by shen-lan** [comment]
1. demo 生成了token  ，但是却没有见到在哪里去`verify`  `token`。
2 .实际测试发现，`token`确实校验生效了。请问是因为`egg-jwt`内部自动做了校验`token`吗？
3. 如果是。假如想存储到`redis`，自己去做校验，该怎么做？
谢谢
